version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - ./app:/app
    env_file: .env.dev
    ports:
      - "5000:5000"
    command: poetry run flask run --host 0.0.0.0 --port 5000
